name: Tests
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'
      
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: '24'

      - name: Setup Clojure
        uses: DeLaGuardo/setup-clojure@13.6.1
        with:
          cli: latest

      - name: Install Node Dependencies
        run: |
          npm install

      - name: Install Clojure Dependencies
        run: |
          clojure -P

      - name: Run tests
        run: |
          npm run test
